[build]
  command = "make build"
  functions = "functions"
[build.environment]
  GO_IMPORT_PATH = "github.com/EugeneHerasymchuk/go-functions-example"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200